# DBSCAN-v1-e2e

run end to end training and display results

In [5]:
## load data
import os
import sys
import tabulate
import pandas as pd
import numpy as np
import logging
import matplotlib.pyplot as plt
import logging
logging.basicConfig(level=logging.INFO)

pd.set_option('display.max_columns', 100)

PATH = '/home/user/pengfei/toubiao/data/training/merged-training.csv'

df = pd.read_csv(PATH)
print(df.shape)
df.head()

(138616, 51)


Unnamed: 0.1  Unnamed: 0                     标段编号                    标段名称  \
0             0           0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）   
1             1           0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）   
2             2           0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）   
3             3           0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）   
4             4           0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）   

           标段创建时间               项目编号         项目编号_1                  所属项目统一代码  \
0  2023/6/20 0:00  B3209250001000020  小区雨污分流及清淤养护工程  2302-320925-89-05-805283   
1  2023/6/20 0:00  B3209250001000020  小区雨污分流及清淤养护工程  2302-320925-89-05-805283   
2  2023/6/20 0:00  B3209250001000020  小区雨污分流及清淤养护工程  2302-320925-89-05-805283   
3  2023/6/20 0:00  B3209250001000020  小区雨污分流及清淤养护工程  2302-320925-89-05-805283   
4  2023/6/20 0:00  B3209250001000020  小区雨污分流及清淤养护工程  2302-320925-89-05-805283   

  所属项目类型   项目所在地      标段最高限价 数据来源                                标段唯一标识  \
0     住建  320925  10032600.0   盐城  001330d3-6f28-4c2d-bdc8-17f1f886d756   
1     住建  320925  10032600.0   盐城  001330d3-6f28-4c2d-bdc8-17f1f886d756   
2     住建  320925  10032600.0   盐城  001330d3-6f28-4c2d-bdc8-17f1f886d756   
3     住建  320925  10032600.0   盐城  001330d3-6f28-4c2d-bdc8-17f1f886d756   
4     住建  320925  10032600.0   盐城  001330d3-6f28-4c2d-bdc8-17f1f886d756   

             开标时间        招标单位统一社会信用代码       招标单位名称        招标代理统一社会信用代码  \
0  2023/6/20 9:00  913209257395801545  建湖县污水处理有限公司  91320925MA23FWC92Y   
1  2023/6/20 9:00  913209257395801545  建湖县污水处理有限公司  91320925MA23FWC92Y   
2  2023/6/20 9:00  913209257395801545  建湖县污水处理有限公司  91320925MA23FWC92Y   
3  2023/6/20 9:00  913209257395801545  建湖县污水处理有限公司  91320925MA23FWC92Y   
4  2023/6/20 9:00  913209257395801545  建湖县污水处理有限公司  91320925MA23FWC92Y   

           招标代理名称  Unnamed: 0_copy               投标人代码          投标人名称  \
0  江苏森达工程项目管理有限公司                0  91320722MA202MXNXU   江苏等优建设工程有限公司   
1  江苏森达工程项目管理有限公司                1  91320922571389910J   盐城海成建筑劳务有限公司   
2  江苏森达工程项目管理有限公司                2  91320891MA20MFQN50   江苏路梦建设工程有限公司   
3  江苏森达工程项目管理有限公司                3  91320600MA25T7723A     江苏华务市政有限公司   
4  江苏森达工程项目管理有限公司                4  91320114MA1Y0J0R27  南京安途达市政工程有限公司   

                 标段编号_copy               标段名称_copy  投标人注册地行政区域代码  \
0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）      320722.0   
1  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）      320922.0   
2  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）      320803.0   
3  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）      320941.0   
4  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）      320115.0   

          投标文件上传时间        投标金额 数据来源_copy  Unnamed: 0_copy.1 BiaoDuanNO 中标人代码  \
0  2023/6/19 23:07  9012047.20        盐城                NaN        NaN   NaN   
1  2023/6/19 16:41  8947616.55        盐城                NaN        NaN   NaN   
2  2023/6/19 17:38  9057869.16        盐城                NaN        NaN   NaN   
3  2023/6/19 16:30  9295487.30        盐城                NaN        NaN   NaN   
4  2023/6/19 22:10  9162643.66        盐城                NaN        NaN   NaN   

  中标人名称 中标时间  中标金额 投标人名称_copy  Unnamed: 0_copy.2              标段编号_copy.1  \
0   NaN  NaN   NaN        NaN             269636  B3209250001000020002001   
1   NaN  NaN   NaN        NaN             269665  B3209250001000020002001   
2   NaN  NaN   NaN        NaN             269048  B3209250001000020002001   
3   NaN  NaN   NaN        NaN             269018  B3209250001000020002001   
4   NaN  NaN   NaN        NaN             269268  B3209250001000020002001   

              标段名称_copy.1          投标人代码_copy       投标联系人电话  \
0  2023小区雨污分流及清淤养护工程（二标段）  91320722MA202MXNXU   18082033198   
1  2023小区雨污分流及清淤养护工程（二标段）  91320922571389910J   15380508080   
2  2023小区雨污分流及清淤养护工程（二标段）  91320891MA20MFQN50   13382318688   
3  2023小区雨污分流及清淤养护工程（二标段）  91320600MA25T7723A   15051347920   
4  2023小区雨污分流及清淤养护工程（二标段）  91320

# feature selection

In [6]:
import logging
logging.basicConfig(level=logging.INFO)

feature_cols = (
    '标段编号',
    '标段名称',
    '标段创建时间',
    '所属项目统一代码',
    '所属项目类型',
    '项目所在地',
    '标段最高限价',
    '标段唯一标识',
    '投标人名称',
    '投标人注册地行政区域代码',
    '投标金额',
    '中标人名称',
    '投标联系人电话',
    'MAC地址',
    '下载招标文件IP',
    '投标文件上传IP'
)
training_df = df[list(feature_cols)]
logging.info('training_df shape: {}'.format(training_df.shape))
display(training_df.head())


标段编号                    标段名称          标段创建时间  \
0  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   
1  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   
2  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   
3  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   
4  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   

                   所属项目统一代码 所属项目类型   项目所在地      标段最高限价  \
0  2302-320925-89-05-805283     住建  320925  10032600.0   
1  2302-320925-89-05-805283     住建  320925  10032600.0   
2  2302-320925-89-05-805283     住建  320925  10032600.0   
3  2302-320925-89-05-805283     住建  320925  10032600.0   
4  2302-320925-89-05-805283     住建  320925  10032600.0   

                                 标段唯一标识          投标人名称  投标人注册地行政区域代码  \
0  001330d3-6f28-4c2d-bdc8-17f1f886d756   江苏等优建设工程有限公司      320722.0   
1  001330d3-6f28-4c2d-bdc8-17f1f886d756   盐城海成建筑劳务有限公司      320922.0   
2  001330d3-6f28-4c2d-bdc8-17f1f886d756   江苏路梦建设工程有限公司      320803.0   
3  001330d3-6f28-4c2d-bdc8-17f1f886d756     江苏华务市政有限公司      320941.0   
4  001330d3-6f28-4c2d-bdc8-17f1f886d756  南京安途达市政工程有限公司      320115.0   

         投标金额 中标人名称       投标联系人电话              MAC地址  \
0  9012047.20   NaN   18082033198  80-2B-F9-8D-2B-D1   
1  8947616.55   NaN   15380508080  0C-9D-92-78-5D-9C   
2  9057869.16   NaN   13382318688  7C-10-C9-C0-01-5E   
3  9295487.30   NaN   15051347920  18-C0-4D-20-B1-CA   
4  9162643.66   NaN  025-85789166  80-32-53-68-03-80   

                                  下载招标文件IP  \
0  2409:8a20:72be:e250:28a4:fd90:f5a8:7da9   
1                            222.188.57.78   
2                          180.125.122.229   
3     240e:3a1:8912:35f0:6b:284f:e990:ea2d   
4                           223.67.185.251   

                                  投标文件上传IP  
0  2409:8a20:72be:e250:5c7f:419e:77f4:2d10  
1                            222.188.57.78  
2                          180.125.122.229  
3     240e:3a1:8912:35f0:6b:284f:e990:ea2d  
4  2409:8a20:8a17:2040:2032:3ffd:210d:495e

# distance definitions

In [7]:
import tqdm

def binary_distance(df_in, col, i, j):
    v1 = df_in.iloc[i][col]
    v2 = df_in.iloc[j][col]
    if v1 == v2:
        return 0
    else:
        return 1
    
def abs_norm_distance(df_in, col, i, j):
    gap = df_in[col].max() - df_in[col].min()
    v1 = df_in.iloc[i][col]
    v2 = df_in.iloc[j][col]
    return np.abs(v1 - v2) / gap

def distance(df_in, col, i, j, method="binary"):
    if method == "binary":
        return binary_distance(df_in, col, i, j)
    else:
        return 1

def get_distance_matrix(df_in):
    n = df_in.shape[0]
    m = df_in.shape[1]
    
    dmat = np.zeros((n, n), dtype=np.float32)
    min_dist = m
    for i in tqdm.tqdm(range(n), total=n):
        for j in range(i + 1, n):
            d = 0
            for col in df_in.columns:
                d += distance(df_in, col, i, j)
            dmat[i,j] = d
            dmat[j,i] = d
            min_dist = min(d, min_dist)

    print('minimum distance: {}'.format(min_dist))
    return dmat
    
dmat = get_distance_matrix(training_df.head(n=100))
print(dmat)
display(dmat)

100%|█████████████████████████████████████████| 100/100 [00:05<00:00, 18.53it/s]

minimum distance: 5
[[0. 8. 8. ... 8. 8. 8.]
 [8. 0. 8. ... 8. 8. 8.]
 [8. 8. 0. ... 8. 8. 8.]
 ...
 [8. 8. 8. ... 0. 7. 8.]
 [8. 8. 8. ... 7. 0. 8.]
 [8. 8. 8. ... 8. 8. 0.]]


array([[0., 8., 8., ..., 8., 8., 8.],
       [8., 0., 8., ..., 8., 8., 8.],
       [8., 8., 0., ..., 8., 8., 8.],
       ...,
       [8., 8., 8., ..., 0., 7., 8.],
       [8., 8., 8., ..., 7., 0., 8.],
       [8., 8., 8., ..., 8., 8., 0.]], dtype=float32)

In [15]:
np.where(dmat == 5)


(array([ 5, 67]), array([67,  5]))

In [16]:
training_df.iloc[[5, 67]]


标段编号                    标段名称          标段创建时间  \
5   B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   
67  B3209250001000020002001  2023小区雨污分流及清淤养护工程（二标段）  2023/6/20 0:00   

                    所属项目统一代码 所属项目类型   项目所在地      标段最高限价  \
5   2302-320925-89-05-805283     住建  320925  10032600.0   
67  2302-320925-89-05-805283     住建  320925  10032600.0   

                                  标段唯一标识         投标人名称  投标人注册地行政区域代码  \
5   001330d3-6f28-4c2d-bdc8-17f1f886d756  江苏摩玛建设工程有限公司      320922.0   
67  001330d3-6f28-4c2d-bdc8-17f1f886d756  江苏烎博建设工程有限公司      320922.0   

          投标金额 中标人名称      投标联系人电话              MAC地址      下载招标文件IP  \
5   9082168.20   NaN  18061601151  F0-2F-74-DE-CC-A1  49.69.63.192   
67  8404308.12   NaN  15961918298                NaN  49.69.63.192   

        投标文件上传IP  
5   49.69.63.192  
67  49.69.63.192

# call DBSCAN

In [15]:
from sklearn.datasets import make_blobs
from sklearn.metrics import pairwise_distances
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt
import numpy as np


# Apply DBSCAN with precomputed distance matrix
dbscan = DBSCAN(eps=7, min_samples=2, metric='precomputed')
labels = dbscan.fit_predict(dmat)
labels

array([-1,  0,  1,  2, -1,  0,  3,  0,  0, -1, -1,  4,  5,  6,  0,  3,  7,
        8,  9,  9,  3,  5,  3, 10, -1,  4,  0, 10, 10, 10, -1, 10,  5, -1,
        4, 11, 12, -1,  9, 11,  0,  9, 11,  3,  3,  9, 10, -1,  4,  4, 10,
       -1,  3,  9, 13,  0, 13,  4, 10, -1,  2, -1, 10,  4,  4, -1, -1,  0,
       10,  3,  6, -1,  7,  0, 13, 12, -1, -1, 14,  9,  6, 10, 14,  3,  4,
        9,  4, 13,  8,  3, -1,  4,  0, -1,  4,  4,  1,  3,  3, -1])

In [11]:
np.where(labels==0)


(array([ 5, 67]),)